# Generated by Django 4.1 on 2022-09-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_category_parent_alter_category_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default=True),
        ),
    ]
